USE [TinTuc]
GO

/****** Object:  Table [dbo].[DANGTIN]    Script Date: 04/25/2021 21:38:10 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DANGTIN](
	[MaDangTin] [int] IDENTITY(1,1) NOT NULL,
	[NgayDang] [date] NULL,
	[MaTinTuc] [int] NULL,
	[ID] [nvarchar](200) NULL,
	[File_DangTin] [nvarchar](max) NULL,
 CONSTRAINT [PK_DANGTIN] PRIMARY KEY CLUSTERED 
(
	[MaDangTin] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

ALTER TABLE [dbo].[DANGTIN]  WITH CHECK ADD  CONSTRAINT [FK_DANGTIN_TAIKHOAN] FOREIGN KEY([ID])
REFERENCES [dbo].[TAIKHOAN] ([ID])
GO

ALTER TABLE [dbo].[DANGTIN] CHECK CONSTRAINT [FK_DANGTIN_TAIKHOAN]
GO

ALTER TABLE [dbo].[DANGTIN]  WITH CHECK ADD  CONSTRAINT [FK_DANGTIN_TINTUC] FOREIGN KEY([MaTinTuc])
REFERENCES [dbo].[TINTUC] ([MaTinTuc])
GO

ALTER TABLE [dbo].[DANGTIN] CHECK CONSTRAINT [FK_DANGTIN_TINTUC]
GO

