USE [TinTuc]
GO

/****** Object:  Table [dbo].[DUYETTIN]    Script Date: 04/25/2021 21:39:30 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DUYETTIN](
	[MaDuyetTin] [int] IDENTITY(1,1) NOT NULL,
	[NgayDuyet] [date] NULL,
	[MaDangTin] [int] NULL,
	[TrangThai] [nvarchar](50) NULL,
	[NgayDuocDang] [date] NOT NULL,
 CONSTRAINT [PK_DUYETTIN] PRIMARY KEY CLUSTERED 
(
	[MaDuyetTin] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[DUYETTIN]  WITH CHECK ADD  CONSTRAINT [FK_DUYETTIN_DANGTIN] FOREIGN KEY([MaDangTin])
REFERENCES [dbo].[DANGTIN] ([MaDangTin])
GO

ALTER TABLE [dbo].[DUYETTIN] CHECK CONSTRAINT [FK_DUYETTIN_DANGTIN]
GO

