USE [TinTuc]
GO

/****** Object:  Table [dbo].[LOAITIN]    Script Date: 04/25/2021 21:39:50 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[LOAITIN](
	[MaLoaiTin] [nvarchar](50) NOT NULL,
	[TenLoaiTin] [nvarchar](200) NULL,
 CONSTRAINT [PK_LOAITIN] PRIMARY KEY CLUSTERED 
(
	[MaLoaiTin] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

