//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANGTIN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DANGTIN()
        {
            this.DUYETTINs = new HashSet<DUYETTIN>();
        }
    
        public int MaDangTin { get; set; }
        public Nullable<System.DateTime> NgayDang { get; set; }
        public Nullable<int> MaTinTuc { get; set; }
        public string ID { get; set; }
        public string File_DangTin { get; set; }
    
        public virtual TAIKHOAN TAIKHOAN { get; set; }
        public virtual TINTUC TINTUC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DUYETTIN> DUYETTINs { get; set; }
    }
}
