//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTT.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.ComponentModel.DataAnnotations;

    public partial class TINTUC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TINTUC()
        {
            this.DANGTINs = new HashSet<DANGTIN>();
        }
    
        public int MaTinTuc { get; set; }
        public string TieuDe { get; set; }
        public string MoTa { get; set; }
        public string File_Link { get; set; }
        public string Hinh_Link { get; set; }
        public string TacGia { get; set; }

        [DataType(DataType.Date)]
        public Nullable<System.DateTime> Ngay_TinTuc { get; set; }

        [DisplayFormat(ConvertEmptyStringToNull = false)]
        public string MaTheLoai { get; set; }

        [DisplayFormat(ConvertEmptyStringToNull = false)]
        public string MaLoaiTin { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DANGTIN> DANGTINs { get; set; }
        public virtual LOAITIN LOAITIN { get; set; }
        public virtual THELOAI THELOAI { get; set; }
    }
}
